# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*test.csproj'
    publishTestResults: false

- task: CmdLine@2
  displayName: 'Create .nupkg file'
  inputs:
    script: 'dotnet pack -o $(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  displayName: 'List contents of artifacts staging directory'
  inputs:
    script: 'ls $(Build.ArtifactStagingDirectory)'
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $projectContents = cat DomainObjects/DomainObjects.csproj
      $packageVersion = $projectContents -match '\d.\d.\d' -replace '(.*)(\d.\d.\d{1,20})(.*)', '$2'
      $packageLocation = '$(Build.ArtifactStagingDirectory)/DomainDrivenDesign.DomainObjects.' + $packageVersion + '.nupkg'
      dotnet nuget push $packageLocation -k $(nugetkey) -s https://api.nuget.org/v3/index.json