# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Create .nupkg file'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'ByPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '0'
    patchVersion: '$(Build.BuildNumber)'

- task: CmdLine@2
  displayName: 'List contents of artifacts staging directory'
  inputs:
    script: 'ls $(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  displayName: 'Publish the nuget package'
  inputs:
    script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)/DomainDrivenDesign.DomainObjects.0.0.1.nupkg -k $(nugetkey) -s https://api.nuget.org/v3/index.json'