# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
       command: 'test'
       projects: '**/*test.csproj'
       publishTestResults: false

    - task: CmdLine@2
      displayName: 'Create .nupkg file'
      inputs:
        script: 'dotnet pack -o $(Build.ArtifactStagingDirectory)'

- stage: Release
  jobs:
  - job: Release
  - deployment: 'DomainDrivenDesign.DomainObjects'
    displayName: 'Deploy DomainDrivenDesign.DomainObjects to nuget!'
    environment: 'Production'
    strategy: 
      runOnce:
        deploy:
          steps:
           - task: CmdLine@2
             inputs:
               script: 'ls $(Build.ArtifactStagingDirectory)'
